apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: event-processor

resources:
  - namespace.yaml
  - configmap.yaml
  - kafka.yaml
  - clickhouse.yaml
  - redis.yaml
  - backend-deployment.yaml
  - consumer-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: event-processor
  app.kubernetes.io/part-of: realtime-event-processor
